### ISSUE TITLE
Macro Compile Error

### ISSUE THREAD

**Issue by jamesward** [njeuk/dbmapper#2]
I'm getting an error that seems related to the macro code:
```
value get is not a member of com.github.mauricio.async.db.RowData
[error]   implicit def rowToBook: RowData => Contact = (r) => DbCodeGenerator.rowToClass[Contact](r)
```

**Comment by njeuk** [comment]
Hi,
My guess is that you are missing the following import on the top of the file with the error:  
`import com.github.njeuk.dbmapper.RowDataExtension._`
The macro generates some code which relies on the RowDataExtension.  
Looking at it with fresh eyes, I realise that the macro probably could just generate all the required code directly, and we could avoid having to do the import.  Maybe for a future release. Hope this helps.
